package at.aau.serg.websocketdemoserver.dto;

public enum MessageType {
    ROLL_DICE, PLAYER_MOVED, CAN_BUY_PROPERTY, BUY_PROPERTY, PROPERTY_BOUGHT,
    EVENT_CARD_DRAWN, RISK_CARD_DRAWN, PAY_TAX, GO_TO_JAIL, SKIPPED, MUST_PAY_RENT,
    ERROR, CURRENT_PLAYER, CASH_TASK, DRAW_EVENT_RISIKO_CARD, DRAW_EVENT_BANK_CARD, PLAYER_OUT_OF_JAIL_CARD, GAME_STARTED
}
