package at.aau.serg.websocketdemoserver.dto;

public enum MessageType {
    ROLL_DICE,
    GAME_STATE,
    ASK_BUY_PROPERTY,
    ASK_PAY_PRISON,
    PAY_PRISON,
    ROLL_PRISON,
    ROLLED_PRISON,

    BUY_PROPERTY,
    GO_TO_JAIL,
    PAY_RENT,
    REQUEST_GAME_STATE,
    EXTRA_MESSAGE,

    DRAW_BANK_CARD,
    DRAW_RISK_CARD,
    PAY_TAX,
    ERROR,
    CURRENT_PLAYER,
    PASS_START,
    BUILD_HOUSE,
    BUILD_HOTEL,
    GAME_STARTED,
    PLAYER_LOST,
    GAME_OVER,
    CASH_TASK,
    PLAYER_OUT_OF_JAIL_CARD,
    DICE_ROLLED,
    END_GAME,
    GAME_ENDED,
}
